### PR TITLE
added planet drewb for lolz

### PR DESCRIPTION
**Pull request by tmwlcx**

### CODE REVIEW

**Review by WilcoxJ — CHANGES_REQUESTED** [review]
need to add planet_drewb.jpeg into /img and add an if value == 'drewb' statement on line 409 similar to the others. Also make drewb.visible = false for the others.

**Comment by tmwlcx** [comment]
try now

**Review by tmwlcx — COMMENTED** [review]
LFG!!!

**Comment by tmwlcx** [comment]
try this!

**Review by WilcoxJ — APPROVED** [review]

**Pull request merged**
